<!ELEMENT CIRCUITS (CIRCUIT+)>
<!ELEMENT CIRCUIT (ETAPE+)>
<!ELEMENT ETAPE (SIGNATAIRES|SIGNATAIRE+)>
<!ELEMENT SIGNATAIRES (SIGNATAIRE+)>
<!ELEMENT SIGNATAIRE (#PCDATA)>
<!ATTLIST CIRCUIT STRUCTURE_RACINE     CDATA #IMPLIED
		  DESCRIPTION          CDATA #REQUIRED>
<!-- Attention : NUMERO doit etre un nombre entier strictement positif -->
<!ATTLIST ETAPE INCLUDE_STRUCT_RACINE  CDATA #IMPLIED
		EXCLUDE_STRUCT_RACINE  CDATA #IMPLIED
		DESCRIPTION            CDATA #REQUIRED
		NUMERO                 CDATA #REQUIRED
		TYPESIGNATURE          (pdfImageStamp|hiddenVisa|visa) #REQUIRED
		TOUTESIGNATURE         (Y|YES|O|OUI|N|NO|NON) #REQUIRED
		PIECEJOINTEOBLIGATOIRE (Y|YES|O|OUI|N|NO|NON) #REQUIRED
		OBLIGATOIRE            (Y|YES|O|OUI|N|NO|NON) #REQUIRED>
<!ATTLIST SIGNATAIRE TYPESIGNATAIRE    (DEMANDEUR|RESPONSABLE|RESPONSABLE_N2|DIRECTEUR_RACINE|AGENT|RESPONSABLE_STRUCT|RESPONSABLE_BRANCHE) #REQUIRED>
