CREATE TABLE `W_MODALITE` (
  `HARPEGEID` varchar(10) NOT NULL,
  `NUMLIGNE` varchar(45) NOT NULL,
  `QUOTITE` int(11) NOT NULL,
  `DATEDEBUT` date NOT NULL,
  `DATEFIN` date NOT NULL,
  PRIMARY KEY (`HARPEGEID`,`NUMLIGNE`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

CREATE TABLE `W_STATUT` (
  `HARPEGEID` varchar(10) NOT NULL,
  `NUMLIGNE` varchar(45) NOT NULL,
  `TYPESTATUT` varchar(45) NOT NULL,
  `DATEDEBUT` date NOT NULL,
  `DATEFIN` date NOT NULL,
  PRIMARY KEY (`HARPEGEID`,`NUMLIGNE`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

CREATE TABLE `W_STRUCTURE` (
  `HARPEGEID` varchar(10) NOT NULL,
  `NUMLIGNE` varchar(45) NOT NULL,
  `IDSTRUCT` varchar(45) NOT NULL,
  `DATEDEBUT` date NOT NULL,
  `DATEFIN` date NOT NULL,
  PRIMARY KEY (`HARPEGEID`,`NUMLIGNE`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

UPDATE `TYPEABSENCE` SET `LIBELLE`='Congé administratif' WHERE `TYPEABSENCEID`='harp';
UPDATE `TYPEABSENCE` SET `LIBELLE`='Absence autorisée par l\'établissement (fête du sport)' WHERE `TYPEABSENCEID`='spec';
UPDATE `TYPEABSENCE` SET `COULEUR`='#99FFFF' WHERE `TYPEABSENCEID`='sup15';
ALTER TABLE `g2t`.`AGENT` CHANGE COLUMN `NOM` `NOM` VARCHAR(80) NOT NULL COMMENT '' , CHANGE COLUMN `PRENOM` `PRENOM` VARCHAR(80) NOT NULL COMMENT '' , CHANGE COLUMN `ADRESSEMAIL` `ADRESSEMAIL` VARCHAR(100) NOT NULL COMMENT '' ;
