UPDATE `TYPEABSENCE` SET `LIBELLE`='Absence autorisée par l\'établissement' WHERE `TYPEABSENCEID`='spec';

-- Personne n'est gestionnaire de RHCONGE pour le moment !!!
-- INSERT INTO COMPLEMENT(HARPEGEID, COMPLEMENTID, VALEUR) VALUES('22216','RHCONGE','O');

-- Mlle Charlotte Becker-Scarpitta => Gestionnaire CET, ANOMALIE
INSERT INTO COMPLEMENT(HARPEGEID, COMPLEMENTID, VALEUR) VALUES('22216','RHCET','O');
INSERT INTO COMPLEMENT(HARPEGEID, COMPLEMENTID, VALEUR) VALUES('22216','RHANOMALIE','O');

-- Mme Murièle Sebert => Gestionnaire CET, ANOMALIE
INSERT INTO COMPLEMENT(HARPEGEID, COMPLEMENTID, VALEUR) VALUES('15280','RHCET','O');
INSERT INTO COMPLEMENT(HARPEGEID, COMPLEMENTID, VALEUR) VALUES('15280','RHANOMALIE','O');

-- Mme Mathilde Lavabre => Gestionnaire ANOMALIE
INSERT INTO COMPLEMENT(HARPEGEID, COMPLEMENTID, VALEUR) VALUES('37474','RHANOMALIE','O');
