CREATE TABLE `LABO_UFR` (
  `LABORATOIREID` varchar(10) NOT NULL,
  `UFRID` varchar(10) NOT NULL,
  PRIMARY KEY (`LABORATOIREID`),
  UNIQUE KEY `LABORATOIREID_UNIQUE` (`LABORATOIREID`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

-- Mapping du labo PRISM vers l'UFR 06
INSERT INTO `LABO_UFR` (`LABORATOIREID`, `UFRID`) VALUES ('UR063_4', 'UF06_3');
