ALTER TABLE STRUCTURE
ADD COLUMN `IDDELEG` VARCHAR(10) NULL DEFAULT '' AFTER `GESTVALIDAGENT`,
ADD COLUMN `DATEDEBUTDELEG` DATE NULL DEFAULT NULL AFTER `IDDELEG`,
ADD COLUMN `DATEFINDELEG` DATE NULL DEFAULT NULL AFTER `DATEDEBUTDELEG`;
