CREATE TABLE `HISTORIQUEAFFECTATION` (
	`AGENTID` VARCHAR(10) NOT NULL,
	`NUMLIGNE` VARCHAR(10) NOT NULL,
	`STRUCTUREID` VARCHAR(10) NULL,
	`DATEDEBUT` DATE NULL,
	`DATEFIN` DATE NULL,
	PRIMARY KEY (`AGENTID`, `NUMLIGNE`)
);
