ALTER TABLE `AGENT` CHANGE COLUMN `HARPEGEID` `AGENTID` VARCHAR(10) NOT NULL ;

ALTER TABLE `ALIMENTATIONCET` CHANGE COLUMN `HARPEGEID` `AGENTID` VARCHAR(10) NOT NULL ;

ALTER TABLE `COMMENTAIRECONGE` CHANGE COLUMN `HARPEGEID` `AGENTID` VARCHAR(8) NOT NULL ;

ALTER TABLE `COMPLEMENT` CHANGE COLUMN `HARPEGEID` `AGENTID` VARCHAR(10) NOT NULL , CHANGE COLUMN `DATEDEBUT` `DATEDEBUT` DATE NOT NULL DEFAULT '1900-01-01' ;

ALTER TABLE `HARPABSENCE` CHANGE COLUMN `HARPEGEID` `AGENTID` VARCHAR(10) NOT NULL , CHANGE COLUMN `HARPTYPE` `TYPEABSENCE` VARCHAR(30) NOT NULL , RENAME TO  `ABSENCERH` ;

ALTER TABLE `OPTIONCET` CHANGE COLUMN `HARPEGEID` `AGENTID` VARCHAR(10) NOT NULL ;

ALTER TABLE `SOLDE` CHANGE COLUMN `HARPEGEID` `AGENTID` VARCHAR(10) NOT NULL ;

ALTER TABLE `STRUCTURE` CHANGE COLUMN `NOMLONG` `NOMLONG` VARCHAR(150) NULL DEFAULT NULL , CHANGE COLUMN `NOMCOURT` `NOMCOURT` VARCHAR(50) NOT NULL ;

ALTER TABLE `TELETRAVAIL` CHANGE COLUMN `HARPEGEID` `AGENTID` VARCHAR(10) NOT NULL ;

ALTER TABLE `DEMANDE` ADD COLUMN `AGENTID` VARCHAR(10) NOT NULL AFTER `DEMANDEID`, ADD INDEX `DEMANDE_INDX` (`AGENTID` ASC);

---------------------------------------------------
-- On récupère le numéro de l'agent de l'ancienne oragnisation BDD
-- pour l'injecter dans la colonne AGENTID de la table DEMANDE
DROP TABLE IF EXISTS DUMMYTABLE;
CREATE TABLE DUMMYTABLE(
  `DEMANDEID` VARCHAR(45) NOT NULL,
  `AGENTID` VARCHAR(10) NOT NULL
);

INSERT INTO DUMMYTABLE(DEMANDEID, AGENTID) SELECT DEMANDE.DEMANDEID, AFFECTATION.HARPEGEID
FROM  AFFECTATION,DECLARATIONTP,DEMANDEDECLARATIONTP,DEMANDE
WHERE DEMANDE.DEMANDEID = DEMANDEDECLARATIONTP.DEMANDEID
  AND DEMANDEDECLARATIONTP.DECLARATIONID = DECLARATIONTP.DECLARATIONID
  AND DECLARATIONTP.AFFECTATIONID = AFFECTATION.AFFECTATIONID;

UPDATE DEMANDE DEM INNER JOIN DUMMYTABLE DMT ON DEM.DEMANDEID = DMT.DEMANDEID
SET DEM.AGENTID = DMT.AGENTID;

DROP TABLE IF EXISTS DUMMYTABLE;
-- Fin de l'injection de l'AGENID dans la table DEMANDE
-------------------------------------------------
  
ALTER TABLE `DECLARATIONTP` ADD COLUMN `AGENTID` VARCHAR(10) NOT NULL AFTER `AFFECTATIONID`, ADD COLUMN `NUMLIGNEQUOTITE` VARCHAR(45) NOT NULL AFTER `AGENTID`;
ALTER TABLE `DECLARATIONTP` ADD INDEX `DECLARATIONTP_INDX` (`AGENTID` ASC, `NUMLIGNEQUOTITE` ASC);

------------------------------------------------
-- On decoupe l'AFFECTATIONID de la table DECLARATIONTP pour definir les colonnes AGENTID et NUMLIGNEQUOTITE
UPDATE DECLARATIONTP SET AGENTID = SUBSTR(AFFECTATIONID,1,INSTR(AFFECTATIONID, '_')-1) WHERE AFFECTATIONID LIKE '%\_%\_%' AND (STATUT = 'V' OR STATUT = 'A') AND SUBSTRING_INDEX(AFFECTATIONID, '_', -1) != 'KO';
UPDATE DECLARATIONTP SET NUMLIGNEQUOTITE = SUBSTRING_INDEX(AFFECTATIONID, '_', -1) WHERE AFFECTATIONID LIKE '%\_%\_%' AND (STATUT = 'V' OR STATUT = 'A') AND SUBSTRING_INDEX(AFFECTATIONID, '_', -1) != 'KO';
--- Fin de la definition des colonnes AGENTID et NUMLIGNEQUOTITE
------------------------------------------------

ALTER TABLE `DECLARATIONTP` DROP COLUMN `AFFECTATIONID`;

CREATE TABLE `QUOTITE` (
  `AGENTID` VARCHAR(10) NOT NULL,
  `NUMLIGNE` VARCHAR(45) NOT NULL,
  `QUOTITE` INT(11) NOT NULL,
  `DATEDEBUT` DATE NOT NULL,
  `DATEFIN` DATE NOT NULL,
  PRIMARY KEY (`AGENTID`,`NUMLIGNE`)
) ENGINE=INNODB DEFAULT CHARSET=LATIN1;

CREATE TABLE `SITUATIONADMIN` (
  `AGENTID` VARCHAR(10) NOT NULL,  
  `NUMLIGNE` VARCHAR(10) NOT NULL,
  `DATEDEBUT` DATE NOT NULL,
  `DATEFIN` DATE NOT NULL,
  `POSITIONADMIN` VARCHAR(15) NOT NULL,
  PRIMARY KEY (`AGENTID`,`NUMLIGNE`)
) ENGINE=INNODB DEFAULT CHARSET=LATIN1;

CREATE TABLE `STATUT` (
  `AGENTID` VARCHAR(10) NOT NULL,  
  `NUMLIGNE` VARCHAR(10) NOT NULL,
  `DATEDEBUT` DATE NOT NULL,
  `DATEFIN` DATE NOT NULL,
  `CODECONTRAT` VARCHAR(20) DEFAULT NULL,
  PRIMARY KEY (`AGENTID`,`NUMLIGNE`)
) ENGINE=INNODB DEFAULT CHARSET=LATIN1;

ALTER TABLE `AFFECTATION` CHANGE COLUMN `DATEMODIFICATION` `DATEMODIFICATION` DATE NULL DEFAULT NULL ;
ALTER TABLE `AFFECTATION` DROP COLUMN `STRUCTUREID`;
ALTER TABLE `AFFECTATION` CHANGE COLUMN `AFFECTATIONID` `AFFECTATIONID` VARCHAR(30) NOT NULL;
ALTER TABLE `AFFECTATION` CHANGE COLUMN `HARPEGEID` `AGENTID` VARCHAR(10) NOT NULL;
ALTER TABLE `AFFECTATION` DROP INDEX `HARPEGEID`;
ALTER TABLE `AFFECTATION` ADD INDEX `AFFECTATION_INDX` (`AGENTID` ASC);

DROP TABLE `DEMANDEDECLARATIONTP`;

DROP TABLE `W_MODALITE`, `W_STATUT`, `W_STRUCTURE`;
